version: '3'

services:
    bigs:
        volumes:
            - ./config:/config
        image: berlinmlst/bigsdb:latest
        restart: always
        container_name: bigsdb
        environment:
            - BIGSDB_POSTGRES_USER
            - BIGSDB_POSTGRES_PASSWORD
            - BIGSDB_PG_ABPACHE_PASSWORD
            - BIGSDB_PG_BIGSDB_PASSWORD
            - BIGSDB_USER_DATABASE
            - BIGSDB_ADMIN_LOGIN
            - BIGSDB_ADMIN_SNAME
            - BIGSDB_ADMIN_FNAME
            - BIGSDB_ADMIN_EMAIL
            - BIGSDB_ADMIN_AFFILIATION
            - BIGSDB_ADMIN_PASSWORD
        ports:
            - "80:80"





