version: '3'

services:
    db: 
        image: postgres:10.4
        volumes:
            - ./config/postgres:/docker-entrypoint-initdb.d
        restart: always
        container_name: bigsdb_backend
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - BIGS_PG_APACHE_PASSWORD
            - BIGS_PG_BIGSDB_PASSWORD

    bigs:
        depends_on:
            - db
        volumes:
            - ./config:/config
        image: berlinmlst/bigsdb:latest
        restart: always
        container_name: bigsdb_frontend
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - BIGS_PG_APACHE_PASSWORD
            - BIGS_PG_BIGSDB_PASSWORD
        ports:
            - "80:80"





