version: '3'

services:
    db: 
        image: postgres:10.4
        volumes: 
            - dbdata:/var/lib/postgresql/data
        restart: always
        container_name: bigsdb_backend
        environment:
            POSTGRES_PASSWORD: cocolis
            POSTGRES_USER: cocolis

    bigs:
        depends_on:
            - db
        volumes:
            - dbdata:/dbdata
            - ./config:/config
        image: bigsdb:01
        restart: always
        container_name: bigsdb_frontend
        ports:
            - "80:80"

volumes:
    dbdata:




